### ISSUE TITLE
Add Transfer Support

### ISSUE THREAD

**Issue by blak3r** [blak3r/yaai#1]
Add ability to transfer the call.

This is currently stubbed out and will be added in 2.1.  I need to figure out how to make a dialog box which will let me select from a pick list of people in the CRM... and find a suitable icon.  

Controller.php already supports transferring.

**Comment by blak3r** [comment]
Made progress on this... Transferring works.  
Need a better dialog to select extension and need to update asterisk log so that the call on person who it got transfered to shows up appropriately...

hmm it might actually... i transfered an outbound call which is kind of weird.

**Comment by chris001** [comment]
Sounds like a plan - I vote for letting the person start typing and let it auto-match with either : 
1) user or employee name (as long as they have an extension number, or "external" phone number (cell phone)),
2) extension number or "external" phone number, for any user OR employee.

**Comment by blak3r** [comment]
I'm currently leaning towards having a special dialog window that pops up. 

In the app global settings allowing a list of strings and extensions. As in most use cases there are only a few extensions they want to transfer to. 

That coupled with a free form extension field for Special cases.

**Comment by chris001** [comment]
How about, instead of a free form extension text box, just cache a list of valid extensions - obtained by querying sugar once per hour?  THe reason is - I'm big on not allowing people to be put int a position where they can/might guess extensions and end up with an invalid extension error, and blame it on the UI being cumbersome or unhelpful.  Picking an extension to forward a caller to should be as dummy-proof as possible.  Zero seconds lost guessing an extension to type in, then typing it, then getting an error popup, then thinking, then repeat... Just scroll the valid list, and click or hit enter.

**Comment by blak3r** [comment]
Chris completely agree.  It could be better. This is one of many features hopefully someone in the community will step up and assist with.

**Comment by blak3r** [comment]
Transferring seems to work 4/5 times.  Occasionally, the caller just gets dropped during the transfer.  I haven't figured out how to reproduce.  If anyone else figures out a pattern, please let me know.

**Comment by chris001** [comment]
Is there a setting to basically log every single thing that the asterisk server is outputting to the asteriskLogger.php ?  Like verbose or all, vs. info + errors, vs. errors only.  If there isn't, one should be made - because I just bet it's some type of message that's slipping past the logger's logic - not getting handled - so the call drops.  Just a hunch though.  To be proved or disproved on closer look at the verbose/all log output.

**Comment by blak3r** [comment]
Transfer is a new action in controller.php.  It sends an ami command directly to the asterisk very similar to how click to dial works.  So, it's not a logger issue per se.

But, yes... getting more information is the key to resolving this issue.

**Comment by chris001** [comment]
Does that ami command return any verbose info that you could log?  In sending an ami command like that, are you essentially setting up a full blown communications channel with the asterisk server, equivalent to what the logger has got going on?  Any way those 2 could share functionality via inheritance from a common base class, or composition  - in order to make catching and logging messages absolutely bulletproof across both?

**Comment by blak3r** [comment]
I know where your going with inhertitance. But in this case no for several reasons. 

Asterisk logger receives events from asterisk. It is read only.  

Controller.php is what sends commands to asterisk such as make a call and transfer. 

I do need to handle errors in controller.php better but I don't think I'll catch anything useful there unfortunately.  Asterisk is kinda flakey on certain things like this. 

Have you seen the project todo wiki page? I updated it yesterday.  There are specific things there I think you could probably answer if you had some time.

**Comment by chris001** [comment]
Let me explain why this bug makes it crystal clear to me, why asteriskLogger.php and controller.php code is ripe for refactoring into a shared common base class.

If this transfer intermittently failing bug is indeed due to a timing issue ( and I suspect it is )... then try the transfer with a far faster way, and see if that fixes it - and it'd be far faster to send that ami command thru the existing tcp connection to the remote asterisk server (the connection that the asteriskLogger is holding on to).

Also, in the aseriskLogger, the database connection is already up - that'd also be faster to execute queries through.

And, the error logging infrastructure in the asteriskLogger is up and running - currently the controller is doing "echo" but it'd be more reliable to troubleshoot this bug, to have both asteriskLogger.php and controller.php log either to the same log file, or a log file side by side with the asteriskLogger's activity log/error log, but using the same code and not duplicating each other's efforts at all.

One of everything!  It's a development credo that really saves your skin in many situations..

But I'll look at the todo wiki also.

**Comment by blak3r** [comment]
Guess we'll have to agree to disagree on this one.  I don't think you fully understand the big picture of the app.  
AsteriskLogger runs as it's own thread.  There's no way for sugarcrm to communicate to it.  

The amount of shared code is under like 6 lines of code.
Open socket, write some text, logout... 

This isn't my first rodeo. :P

**Comment by chris001** [comment]
Sorry - didnt meant to imply that.

But - even for code running in separate threads (asteriskLogger running in its own process on the server, and controller.php called by the user's web browser) - a shared base class - or composed objects - is really great, and practically required, for consistency and high quality.

And to avoid the dreaded difficult to maintain "God object" anti-pattern.  http://www.codeproject.com/Articles/187230/What-not-to-do-Anti-Patterns-and-the-Solutions

Each thread - controller and asteriskLogger - needs to do a number of identical things to talk to the asterisk server.  Load login parameters from the settings, log in, retry when they hit communication errors with the remote (or local) server, write to the error/event log, read/write to mysql, and to do all of this with the most resilient code - because it's literally the same code - not copy/pasted - just one (or more) objects or classes.  

When you think about it you realize - there is no reason for each thread to have its own separately developed code for this identical functionality. And plenty of reasons not to - they get out of sync, then one works and the other doesn't, and it's a nightmare.
