### ISSUE TITLE
Call not associated with "Lead"

### ISSUE THREAD

**Issue by jgirdner** [blak3r/yaai#105]
I would first like to say thank you for the outstanding Sugar Plugin.  It is going to come in real handy for my sales team.

I have one issue that I can't seem to resolve.  My sales staff works of the Leads in Sugar and my support department works on Accounts and Contacts.  We don't convert a lead into an account until after they have signed up.

Right now it seems like outbound and inbound calls on "Leads" are not creating the logged call for the record that either was called or called in.  I am not sure if this was done by design or if it is a bug.  It works fine when logging calls to Accounts or Contacts.  This problem only seems to exist on Leads.

**Comment by blak3r** [comment]
Hi Jason,

This is a limitation. Please send me an email my address is in profile. 

~blake

**Comment by cubicova17** [comment]
@blak3r so, is "Leads" module support planned/developed in dev versions(V3)?
Do you know anyone to succeed in adding this functionality or that's an open task to do?

**Comment by blak3r** [comment]
@cubicova17 leads support isn't going to be in the next release. 

It's definitely.a frequent request. We'd likely refactor so that itd also support custom modules as well. 

Leads isn't a feature that my company uses (which is why I originally got involved in yaai).  I have competing interests for my time and unfortunately donations to date have totaled $10. Was hoping a company would fund that development or a couple companies would pool together for that feature. This is a business app after all. 

I have some additional ideas for a pro version of yaai that would include a mobile app (so you could be notified of whos calling when on your smart phone) and have been thinking at that time maybe having leads support be an additional pro feature that people would pay for.  Kind of the freemium model. Keeping contacts and accounts free but having leads, custom modules, and mobile support for a nominal fee. 

Feel free to shoot me an email (see my github profile) to discuss more definitely trying to gather more market research at this time.

Btw thanks for editing the user manual wiki page.  Appreciate the help!

**Comment by maotm** [comment]
Hi,
Yes, I'd sure pay for leads support, and possible for installation.
I went all the trouble to install Asterisk, FreePBX to be able to use the app in Sugar, just to find out it isn't actually working on leads. 
Following the "normal" flow in Sugar: leads - > accounts with contacts, I assumed it must work first on leads.
I'm sure many more are interested.

**Comment by blak3r** [comment]
Sorry man.   I guess I should I should put that in red somewhere.
Send me an email plz my address is in my profile.

**Comment by OmarRodriguezT** [comment]
We were able to do it, thank you for all your help on this matter.
