### ISSUE TITLE
popup after reload page

### ISSUE THREAD

**Issue by bickus** [blak3r/yaai#117]
Is it normal, that I can see popup window only after reloading SugarCRM page and may i somehow to get round this?
Thnx for answer.

**Comment by blak3r** [comment]
Definitely not normal.  Do you have Pro or CE?  I got a beta version of V3 I could give you to try but it has a couple bugs with AJAXUI that still need to be worked out.  Send me an email is in my github profile.

Also, check your browser console.  (right click and inspect element and see if there are any errors).

**Comment by blak3r** [comment]
Анастасия Кулешова On Wed, Feb 27, 2013 at 4:23 AM,  wrote (in an email):

Very strange... today I see popup while inbound call without refreshing, and (or) when outbound call is finished.
Nothing strange in log.
I tested a lot on different computers yesterday, but today looks ok... 
Anyway, thaks for your help and sorry, that I've waisted your time.
And thanks for v3,  I'll try to provide you some helpfull feedback.

**And if you can answer - popup shows with delay 1-2 seconds, is there some way to reduce it?**

**Comment by blak3r** [comment]
Check your ajax poll rate in the config settings.
The default i believe is 5000.  (5 seconds)

That's how often it checks for new calls.  So, the max amount of time it'd take for a call popup is 5000 seconds.  On average it'd be 2.5s.

If you reduce it to 2000 then max time would be 2s.  But, would average about 1s.

The only downside of this is it'll increase your server load some.  If you don't have very many users then you should be fine but you'll want to monitor the performance impact is has on your server.

Make sure you have mysql_query_cache turned on.  Otherwise, you'll be performing a lot of expensive lookup queries whenever you have an inbound call that doesn't match any phone numbers in your crm.  Once it does match, it stops doing the expensive lookups... query cache will cache the queries until someone updates a record in one of the tables.

As for why it's working today... did you just update it the day before?
Perhaps you had old javascript code being cached or something.  

Please do give V3 a try... I noticed when I installed it on one box today that call_record_id wasn't being set.  You'll be able to see this by looking at the log and it'll say something like "Successfully created a call record with id=".

No idea why it was doing that on this particular box... that code hasn't been changed in a very long time.  Need to investigate it further.

**Comment by bickus** [comment]
Nothing wasn't changed from yesterday for pure test.
Thanks for detailed answer,  I'll try V3 couple days on different systems.
