### ISSUE TITLE
Click To Dial Works, but no call notification windows appear

### ISSUE THREAD

**Issue by shyrikoff** [blak3r/yaai#12]
Try to connect sugarcrm with asterisk pbx with the plugin yaai.. but something goes incorrect...

When I make a call from sugar to contact i receive the incomming call on my softphone, accept it and then it redirected to the contact's number. 

The problem is when I calling, there is NO popup window with the information. How can I fix it and who is responsible for it?! 

Thank you for you suggestions :)

asteriskLogger.php has no errors. the log file has been added to the attachments.

Software:
ubuntu server 10.04 LTS 
Asterisk 1.8 
php 5.3.2 
mysql 5.1.61 
sugarcrm 6.4.3 CE 
Yaai 2.0.3

**Comment by blak3r** [comment]
I looked at your log.  You appear to be testing with an internal extension.  Try a real phone number.
Internal to Internal calls are ignored.

INTERNAL call detected, Deleting Call Record 375f0e0d-0e6c-6fe8-a3c9-4fa42c2b93b5 affected: 1 rows.

**Comment by shyrikoff** [comment]
Ok, where have you been!!! I'd formatted servers HD 2 hours before!!! :(

The aim of the system is to transfer calls using my astesrisk server through one more and only then to PSTN. Will it work correctly?! 
What do you mean when you are talking about internal and external numbers? 
If I will merge 2 different asterisk servers, their numbers will be internal or not?!

Thank you for you answer. )

**Comment by blak3r** [comment]
RE: Where have I been...
I live on the east coast of USA... and I have a full time job.  I replied to you in the middle of my work day.  This is an open source project you should consider yourself very lucky to have gotten a response back 7 hours after you posted.

RE: Will it work.
I'm not really sure if it'll work for you or not.  You'll probably have to get your hands dirty.

In your example you dialed 1001.  If you look at the Dial event, you'll see a channel and a destination.  One of those needs to look like something other then SIP/1001... Both of them match the internal line regular expression.

Here's what the dial event looks like on my setup.  You'll notice the 
channel == SIP/754-000006da  <-- There is a regular expression which says this is an internal line (since it's an extension off our PBX)
destination == SIP/Flowroute-0000006db <-- This is a call to a number outside the PBX.  We use a company called flowroute for our sip trunks.

The way asteriskLogger works is it looks at the Channel and Destination to find out whether or not the call is an INBOUND or OUTBOUND call this way.  If both channel and destination are recognized as an INTERNAL call, then we do not create a new call notification.  For some other technical reasons which I can't get into, this is neccessary as there are a lot of Dial events that will occur when you make calls to ring groups and you need to delete the internal ones otherwise you'll get thousands of incorrect events.

! --- Event -----------------------------------------------------------
!                Event --> Dial
!            Privilege --> call,all
!             SubEvent --> Begin
!              Channel --> SIP/754-000006da
!          Destination --> SIP/Flowroute-000006db
!          CallerIDNum --> 4436741607
!         CallerIDName --> A Telephone
!             UniqueID --> 1336422205.3012
!         DestUniqueID --> 1336422205.3013
!           Dialstring --> Flowroute/13017923484
! ---------------------------------------------------------------------

**Comment by shyrikoff** [comment]
The problem was in using php5.3.2 
After the downgrade to php5.2.10 - almost everything works great! Unfortunately it could not open imap v5.2.6 and mcryp v5.2.6 libraries.
Thank you for your helping!

**Comment by blak3r** [comment]
Do you have any idea what part of php 5.3.10 causes problems?

I use 5.3.6

**Comment by shyrikoff** [comment]
Unfortunately, my knowledge in php are very poor. Just found somewhere in russion-speaking forums they were also discussing the problems with integration yaai and sugarcrm. 
One of the reason was incompatibility of php version 5.3.\* That was the reason to try 5.2.*

And thank you for your comments

**Comment by shyrikoff** [comment]
Blak3r, I think it might be interesting for you. I've found a syntax error on line 434 asteriskLogger.php file

logLine("\* {e['UniqueId']} CallerID  Changed to: $tmpCallerID\n"); 

instead of logLine("\* ${e['UniqueId']} CallerID  Changed to: $tmpCallerID\n");

**Comment by shyrikoff** [comment]
Tried to use yaai with php 5.3.2 again. The follow mistakes appeared:
PHP Warning: Attempt to modify property of non-object in /var/www/include/nusoap/nusoap.php on line 6160
and there are now pop-up windows.

But in php 5.2.10 works great!

Also I do not understand if yaai makes list of made calls, or it could connect with asterisk monitor to make able to listen them from crm?!

**Comment by blak3r** [comment]
Your logline comment is a bug... technically it should be 

   logLine("\* {$e['UniqueId']} CallerID Changed to: $tmpCallerID\n");

I get those PHP warnings also.  They don't seem to matter.  I don't know why it'd work now.

It's theoretically possible to add functionality like you mentioned.  But, would take some work. 

How many people are you running on yaai right now?  I'm just curious.

**Comment by shyrikoff** [comment]
That's my first experience with YAAI. :) 

I have 2 separate severs running asterisk and my aim is to connect them with sip. 
I still have problems with mixing caller id. At another sever it is written that xxx calls xxx (the same in asterisk mixmonitor feature).

**Comment by mattchis** [comment]
Hey blak3r,

I run php 5.3.10 and I too am not seeing the pop window when a new inbound call is placed.  I also get the same error running the Launcher:
Warning: Attempt to modify property of non-object in include/nusoap/nusoap.php on line 6160

Here is what I am running:
Sugar 6.4.4 CE
YAAI 2.3.0.9
Asterisk 1.6.0.26

Any insight/help is greatly appreciated.

Thanks,
Mattchis

**Comment by blak3r** [comment]
Did you look at the user manual?  There's a troubleshooting section for this case.  That warning doesn't mean anything.

**Comment by mattchis** [comment]
Thanks for the rapid reply!

I am an idiot.  LOL  My AMI config permissions were all wrong.  I set both to "all" and it has fixed the issue.

Thanks for the help!

Thanks,
Mattchis

**Comment by blak3r** [comment]
cool.  They certainly can be tightened up but I've been too lazy to figure out the exact ones necessary.  It's not really a good idea to have all privileges.  

Also just curious, what's the size of your company - how many are going to be using it?

**Comment by mattchis** [comment]
I am an IT consultant for the company.  One of the big things they want from their CRM is PBX and Outlook integration.  There will be roughly 9 employees using it in the beginning.

Thanks,
Mattchis
