### ISSUE TITLE
asteriskLogger SOAP login failed

### ISSUE THREAD

**Issue by neomax** [blak3r/yaai#21]
When asteriskLogger start, 
! Trying SOAP login endpoint=[http://localhost/crm/soap.php] user=[cid] password=[6508b.......ef1e7]
PHP Warning:  Attempt to modify property of non-object in /var/www/crm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/crm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/crm/include/nusoap/nusoap.php on line 6160
PHP Warning:  Attempt to modify property of non-object in /var/www/crm/include/nusoap/nusoap.php on line 6160
! Successful SOAP login id= user=cid GUID=
# 

No login id 

Software:
Ubuntu Server 11.04
PHP 5.3.5
sugarcrm 6.4.2 CE 
yaii 2.3.0.9

**Comment by blak3r** [comment]
Happens on my instance also. Everything still works. It's probably something pretty easy to resolve I just haven't looked into it.

**Comment by neomax** [comment]
But I receve no  SOAP login id
and it make no records in Sugar

**Comment by blak3r** [comment]
Ahh... I see.  Hmm... is your asterisk logger able to find your config file?

**Comment by blak3r** [comment]
Nevermind... if it wasn't able to see your config file it wouldn't have retrieved your password which I see it does.

Is your site_url set properly (that's a property in your config.php or config.override.php file)...

To test if your site url is set properly...  is this the url you goto to get into your sugarcrm: http://localhost/crm ? or should that be http://localhost/sugarcrm

Obviously something is failing in the login method.  It's a pretty simple method so not too much that could go wrong.  I added some code that will detect a failed login by looking at the userGUID and sessionID variables so that misleading successful message isn't printed for people in the future.  

It'd be best to figure out how to handle soap errors in that wrapper class but don't have time.

```
   class SugarSoap extends nusoapclient
   {
      public $sessionid;
      public $auth_array;

    function __construct($endpoint, $something, $auth_array)
    {
        $this->auth_array = $auth_array;
        parent::__construct($endpoint, $something);
        $this->login();
    }

    function login()
    {
        $result          = parent::call('login', $this->auth_array);
        $this->sessionid = $result['id'];
        //print_r($result);
        return ($result);
    }

    function call($method, $params)
    {
        $params['session'] = $this->sessionid;
        $result            = parent::call($method, $params);
        if (is_array($result) && array_key_exists("error", $result) && $result['error']['number'] != 0) {
            $this->login();
            $result = parent::call($method, $params);

        }
        //print_r($result);
        return ($result);

    }
}
```

**Comment by neomax** [comment]
Now it's work.
I was wrong when i change

$sugarSoapEndpoint   = $sugar_config['site_url'] . "/soap.php";
to
$sugarSoapEndpoint   = "http://localhost/crm/soap.php";

is it posible to change sugarSoapEndpoint manualy in asteriskLogger to
different one than in sugar config? 

Thanks for your help.

**Comment by blak3r** [comment]
No there isn't.
Why would you want to change sugarSoapEndpoint manually?

**Comment by neomax** [comment]
for example if server listen on non standard port

**Comment by blak3r** [comment]
Your site URL should have that non standard port in it.
