### ISSUE TITLE
Bug: Inbound call is not associated with recently created contact

### ISSUE THREAD

**Issue by Guard1an** [blak3r/yaai#25]
When call is received and "Create New" is clicked, after contact is saved:
the call popup displays the correct contact data.
After clicking on Save comment and opening the call history the associated contact is missing.

**Comment by blak3r** [comment]
Yes, I think if the contact is created after the call is over it doesn't get saved. 

~blake

**Comment by blak3r** [comment]
@Guard1an I'm revisiting this issue (doing some housecleaning)...

Call record isn't associated with a contact until the call is hungup.

As a result, if you create a new lead but don't save the lead before you hang up... the call isn't going to get associated with them in them.  This is somewhat misleading because the call popups will begin displaying the new contact name as soon as you create the new contact.

**Comment by Guard1an** [comment]
I've already solved this problem. Will send you the fix soon.

On Fri, Jun 29, 2012 at 7:51 AM, Blake Robertson <
reply@reply.github.com

> wrote:
> 
> @Guard1an I'm revisiting this issue (doing some housecleaning)...
> 
> Call record isn't associated with a contact until the call is hungup.
> 
> As a result, if you create a new lead but don't save the lead before you
> hang up... the call isn't going to get associated with them in them.  This
> is somewhat misleading because the call popups will begin displaying the
> new contact name as soon as you create the new contact.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/blak3r/yaai/issues/25#issuecomment-6649365

## 

ó Õ×ÁÖÅÎÉÅÍ,
óÔÏÒÏÖÅ× áÎÄÒÅÊ

**Comment by blak3r** [comment]
@Guard1an Any chance you could post your fix?  I might have time to work on yaai this weekend.

**Comment by blak3r** [comment]
@Guard1an bump.

**Comment by randomf** [comment]
Any news in this area? This bug also affects me.

**Comment by Guard1an** [comment]
Hi Blake,

Sorry for keeping silence for the long time.

I'm completely overloaded for the passed couple of months and can't find
any time to work on the YAAI module.

I can send you the working copy of the module I have. You can compare it
with the original version and create the patch.

What do you think?

Does github forward the mail attachements or would I send it to your email
directly?

Please give me a sign.

Regards,
Andrew

On Thu, Oct 4, 2012 at 5:57 PM, randomf notifications@github.com wrote:

> Any news in this area? This bug also affects me.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/blak3r/yaai/issues/25#issuecomment-9144196.

## 

ó Õ×ÁÖÅÎÉÅÍ,
óÔÏÒÏÖÅ× áÎÄÒÅÊ

**Comment by Guard1an** [comment]
Btw, the module performance is very slow.

I've optimized the queries a bit to use indexes and avoid REGEXP but it
still takes about 3 seconds multiplied by the number of opened calls to
retrieve the AJAX response.

I have three managers working with CRM and thay claim on the performance
issues everytime(

Have you made any improvements in the latest revisions?

On Thu, Oct 4, 2012 at 6:15 PM, Andrew Storozhev <
andrew.storozhev@googlemail.com> wrote:

> Hi Blake,
> 
> Sorry for keeping silence for the long time.
> 
> I'm completely overloaded for the passed couple of months and can't find
> any time to work on the YAAI module.
> 
> I can send you the working copy of the module I have. You can compare it
> with the original version and create the patch.
> 
> What do you think?
> 
> Does github forward the mail attachements or would I send it to your email
> directly?
> 
> Please give me a sign, andrew.storozhev@gmail.com
> 
> Regards,
> Andrew
> 
> On Thu, Oct 4, 2012 at 5:57 PM, randomf notifications@github.com wrote:
> 
> > Any news in this area? This bug also affects me.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/blak3r/yaai/issues/25#issuecomment-9144196.
> 
> ## 
> 
> ó Õ×ÁÖÅÎÉÅÍ,
> óÔÏÒÏÖÅ× áÎÄÒÅÊ

## 

ó Õ×ÁÖÅÎÉÅÍ,
óÔÏÒÏÖÅ× áÎÄÒÅÊ

**Comment by blak3r** [comment]
@Guard1an it doesn't appear to have attached the attachments. :/
Nor does it appear to have a way of attaching them to issues.  

You could email them to me.  Or if it's just one file put it on paste bin.  

As for performance, there has been some but not much.  There are a couple threads on here about ideas.  @miksir had some good ideas which will definitely help performance.

3 seconds seems reallly long.  What country are you in?  Perhaps it's opencnam integration that's trying on every request.  That's an issue we recently addressed.  

The other good idea in the interim is to empty your asterisk_log table.  Since that table is the one that gets scanned on each ajax call... there are obviously huge performance benefits of clearing it out from time to time.  There really isn't any good reason to keep that data around... it's not reportable in sugar.  

So, could just be cleared out every night... I'm kind of a stat freak so I have been pushing the records to a backup file instead.  Perhaps there is a simple sql command to move a row from one table to another and that way we could have asterisk_log_archive and prune the db everything.
