### ISSUE TITLE
Can't match number to account or contact

### ISSUE THREAD

**Issue by papaja** [blak3r/yaai#27]
SugarCRM 6.5
Asterisk extension 2.3

I edited preg_replace code in findSugarAccountByPhoneNumber and findSugarObjectByPhoneNumber to allow 9 numbers, but it still can't find account or contact by phone.

I get:
PHP Notice:  Undefined index: string in /var/www/html/SugarCRM/custom/modules/Asterisk/asteriskLogger.php on line 1354
! Warning: SOAP error 10

**Comment by papaja** [comment]
Made some progress by switching to php native soap...

**Comment by blak3r** [comment]
I committed some fixes today.  Probably not related to your issue but may be worth looking at.

**Comment by papaja** [comment]
I managed to get matching working. I adjusted regex and web services calls. Now I can't get "Click to dial" button to make a call.

Anyway thanks for your efforts.

**Comment by blak3r** [comment]
Getting Click to Dial working should be very easy.  That's usually the
easiest thing.

From the user manual:

Click To Dial isn't working

Getting click to dial working has less dependencies then getting inbound
call windows working. So, it's recommended that you attempt this first.

These are the dependencies:
1. Asterisk AMI settings are configured properly.
2. The Dial Command settings are wrong. The default is something like
   /SIP###, you may need to edit that.
3. I don't think so but maybe the dialout prefix... If this isn't
   configured properly I would expect your local phone to ring but then you
   wouldn't get connected to the remote person.

How to debug: Open up Chrome, right click on the page somewhere and do
"Inspect Element". Then, click on the Network tab. After you click on the
icon a new index.php call should popup (make sure you get the one for
CallCreate instead of Listener as they'll popup every 5s or so also. In the
response is the result of the AMI login and CreateCall request. So, you
should be able to see a useful error message hopefully.

On Thu, Jun 28, 2012 at 5:29 PM, papaja <
reply@reply.github.com

**Comment by blak3r** [comment]
@papaja Could you please post what you did to make things work for you in case it'll help others?

**Comment by papaja** [comment]
It means I would have to copy/paste entire asteriskLogger.php. I'm afraid I would just confuse someone because I have replaced all nusoap calls with php soap calls, deleted some comments and adjusted regex in few places.

**Comment by blak3r** [comment]
hmm... you can't isolate out your change?
I think the nusoap replacement would be good to have as well.

It's to your advantage to get your changes merged so that you can upgrade
as we make changes.

On Fri, Jun 29, 2012 at 12:03 PM, papaja <
reply@reply.github.com

**Comment by trustmaster** [comment]
@papaja could you paste your regexp adjustments alone? Usually this is what really matters when you fix matching.

+1 for nusoap 2 php soap replacement. It should be a separate pull request though.

**Comment by papaja** [comment]
Here are the asteriskLogger.php modifications that I believe would benefit everyone:
// Fetch Asterisk dialprefix - must strip this from inbound callerIDs if set
$calloutPrefix = isset($sugar_config['asterisk_prefix']) ? $sugar_config['asterisk_prefix'] : "";
echo ("# Callout prefix is [$calloutPrefix]\n");

$callinPrefix = isset($sugar_config['asterisk_dialinPrefix']) ? $sugar_config['asterisk_dialinPrefix'] : "";
echo ("# Callin prefix is [$callinPrefix]\n");

Regex for finding account/contact by phone number should not assume maximum length of 7 numbers. Here is my take:
    $aPhoneNumber = preg_replace('/\D/', '', $aPhoneNumber); // removes everything that isn't a digit.
    if (preg_match('/([0-9]{3,})$/', $aPhoneNumber, $matches)) {
        $aPhoneNumber = $matches[1];
    }

Other changes that I've made are much more invasive and I'm afraid to post them before I test them.
