### ISSUE TITLE
$needle<->$haystack swap

### ISSUE THREAD

**Issue by bubuka** [blak3r/yaai#55]
Hello!

I have found maybe a mistake in the asteriskLogger.php

Original:
function startsWith($haystack, $needle)
{
    $length = strlen($needle);
    return (substr($haystack, 0, $length) === $needle);
}

Working:
function startsWith($needle, $haystack)
{
    $length = strlen($needle);
    return (substr($haystack, 0, $length) === $needle);
}

Regards

**Comment by blak3r** [comment]
Each function does the same thing.  Are you suggesting that since the adage is you search for a needle in a haystack that needle should be the first argument?

I could potentially agree with that.  But, I think the php convention is the way I currently have it.

From PHP Manual:

```
string strstr ( string $haystack , mixed $needle [, bool $before_needle = false ] )
```

Let me know if I missed something.  I always welcome code critiques so thanks for taking a close look.

**Comment by bubuka** [comment]
Ok!

Of course. The sample is ok.

Then you must here to swap the variables  $calloutPrefix<->$tmpCallerID:

if (startsWith($calloutPrefix,$tmpCallerID)) {
                                                logLine ("\* Stripping callout prefix: $calloutPrefix\n");
                                                $tmpCallerID = substr($tmpCallerID, strlen($calloutPrefix));
                                        }

Because the $calloutPrefix is a $needle and the $tmpCallerID is the  $haystack. :)

Somwere must changeing.

Regards

**Comment by blak3r** [comment]
Your absolutely correct about that! 
Thanks!

~blake

**Comment by blak3r** [comment]
Fixed it in latest commit.
