### ISSUE TITLE
Make dialout prefix optional

### ISSUE THREAD

**Issue by trustmaster** [blak3r/yaai#66]
Some asterisk configurations don't use dialout prefixes. Currently if I leave the dailout prefix empty it is reset to "1". I suppose empty dialout prefix should be allowed instead.

This can be achieved by either setting

``` php
$asterisk_config['asterisk_prefix'] = '';
```

and

``` php
$javascript->addFieldGeneric("asterisk_prefix", "varchar", $mod_strings['LBL_ASTERISK_PREFIX'], FALSE, "");
```

in modules/Configurator/asterisk_configurator.php

**Comment by blak3r** [comment]
There was a bug that was identified about a month or two ago where the dialout prefix was hardcoded to 1 in asteriskLogger. 

Is it possible you're running off an older version? I did some searching and couldn't find the commit or issue.

Quick way to test would be to set the dialout prefix to something like 9 and see if it's still setting it to 1.  If it's not... then might be a new bug.

**Comment by trustmaster** [comment]
AsteriskLogger is alright. This bug affects callCreate.php so that
click2call always dials 1 as a prefix if I want to set it empty. I've fixed
it the way described above.
21.09.2012 9:26 ÐÏÌØÚÏ×ÁÔÅÌØ "Blake Robertson" notifications@github.com
ÎÁÐÉÓÁÌ:

**Comment by blak3r** [comment]
Did changing those two lines actually work for you?

I think I also need to change the tpl code from an empty to an issset.  What's happening is the value is getting set in the config... but then the next time you go into the config area it sees that the variable is empty and so it puts the default value in.

I could have an error in my addGenericField portion.  Just wanted to confirm though before I go too far down that path.

I basically wrote a script that generates everything based on some meta data.  So, adding properties in the future will be much easier.  And my autogenerated code fixed whatever the problem was with the stupid soap pass.

Hope to finish is up tomorrow... off to bed for now...

**Comment by trustmaster** [comment]
Yes it did.

It sees that the value is empty and resets it to default, but default is empty in my case as well.

**Comment by blak3r** [comment]
Closing this issue as the latest commit should handle this now.

**Comment by southwestcrm** [comment]
I changed these two lines of code, ran a quick repair and rebuild in Sugar and still the dial out does not continue to dial the click upon number. Only my ext rings with a non existent call out. ummmm  

I see you just closed the issue - not sure what to extract from the latest post.. Any help would be appreciated :)

**Comment by blak3r** [comment]
@southwestcrm your problem is something probably entirely different.  Please see the section in the user manual about getting click to dial working.
